name: Deploy to GitHub Pages (with lint)

on:
  push:
    branches: [ main ]
    paths:
      - "index.html"
      - "assets/css/style.css"
      - "assets/js/script.js"
      # paths:
      #   - "**"   # enable later to deploy on ANY change
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      # HTML — HTMLHint
      - name: Create .htmlhintrc
        run: |
          cat > .htmlhintrc <<'EOF'
          {
            "doctype-first": false,
            "tagname-lowercase": true,
            "attr-value-double-quotes": true,
            "id-unique": true,
            "src-not-empty": true,
            "title-require": true
          }
          EOF
      - name: Lint HTML
        run: npx --yes htmlhint "**/*.html" --config .htmlhintrc

      # CSS — stylelint (simple built-in rules so no extra packages)
      - name: Create .stylelintrc.json
        run: |
          cat > .stylelintrc.json <<'EOF'
          {
            "rules": {
              "color-no-invalid-hex": true,
              "block-no-empty": true,
              "declaration-block-no-duplicate-properties": true,
              "string-no-newline": true
            }
          }
          EOF
      - name: Lint CSS
        run: npx --yes stylelint "**/*.css"

      # JS — ESLint (recommended rules, fail on warnings)
      - name: Create .eslintrc.json
        run: |
          cat > .eslintrc.json <<'EOF'
          {
            "env": { "browser": true, "es2021": true },
            "extends": "eslint:recommended",
            "parserOptions": { "ecmaVersion": 2021, "sourceType": "script" },
            "rules": {
              "no-unused-vars": "warn",
              "no-undef": "error"
            }
          }
          EOF
      - name: Lint JS
        run: npx --yes eslint@9 "**/*.js" --max-warnings=0

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
