name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - "index.html"    # only publish when index.html changes
      - "assets/css/style.css"
      - "assets/js/script.js"
      # paths:
      #   - "**"   # enable later to deploy on ANY change
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Download the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js so we can run lint tools
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3: Install ESLint
      - name: Install ESLint
        run: npm install --global eslint@8.57.0

      # Step 4: Run ESLint with inline rules (no config file in repo)
      - name: Run ESLint check
        run: |
          npx eslint@8.57.0 "assets/js/**/*.js" \
            --no-eslintrc \
            --env browser \
            --parser-options '{"ecmaVersion": 2021, "sourceType": "script"}' \
            --global emailjs:true \
            --rule 'no-undef:error' \
            --rule 'no-unused-vars:warn' \
            --max-warnings=0

      # Step 5: Upload site files as GitHub Pages artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
