name: Rollback Pages
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to rollback to (e.g., v2025.08.16-0406). Leave blank for latest."
        required: false
        default: ""

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: rollback-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout full history so we can see tags
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # important: fetch all tags

      # 2) Decide which tag to use (input or latest)
      - name: Resolve tag
        id: resolve
        run: |
          set -euo pipefail
          INPUT_TAG="${{ github.event.inputs.tag }}"
          if [ -n "$INPUT_TAG" ]; then
            TAG="$INPUT_TAG"
          else
            TAG="$(git tag --sort=-creatordate | head -n 1 || true)"
          fi
          if [ -z "${TAG:-}" ]; then
            echo "No tags found. Create a deploy tag first." >&2
            exit 1
          fi
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"
          echo "Rolling back to: $TAG"

      # 3) Check out that tag
      - name: Checkout tag
        run: |
          set -euo pipefail
          git checkout "tags/${{ steps.resolve.outputs.TAG }}" --detach
          git rev-parse --short HEAD

      # 4) Build only site files (avoid zipping .git, workflows, etc.)
      - name: Build static site
        run: |
          rm -rf _site && mkdir -p _site
          cp -R index.html assets _site/

      # 5) Upload and deploy to GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy tagged version
        uses: actions/deploy-pages@v4
